"""The verb taxonomy: verb features and the verb tree.

Verbs are generated by the noun generator's own machinery, applied to a second tree. The verb
features ``VF.<n>`` are binary, all free, with one shared base rate, and have no rules among
themselves. The verb tree is built exactly like the noun tree (superordinates, roles, children,
distinct leaves) from ``verbs.taxonomy`` and ``verbs.inheritance``, drawing everything from the
``taxonomy:verb_tree`` stream. The leaves of the verb tree are the verbs. Verbs have no instances.
With ``verbs.taxonomy.depth`` 1 and no defining features, verbs are independent of each other.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from semantic_world.taxonomy.config import Config, VerbsConfig
from semantic_world.taxonomy.features import Feature, FeatureSet
from semantic_world.taxonomy.rules import RuleSet
from semantic_world.taxonomy.streams import Streams
from semantic_world.taxonomy.tree import Category, Tree, build_tree

VERB_FEATURE_TYPE = "vf"


@dataclass(frozen=True)
class VerbTaxonomy:
    features: FeatureSet
    """The verb features ``VF.1`` to ``VF.<count>``, all free."""
    rules: RuleSet
    """An empty rule set over the verb features (verb features have no rules)."""
    tree: Tree
    """The verb categories, labelled ``V1``, ``V1.1``, ...; the leaves are the verbs."""

    @property
    def verbs(self) -> tuple[Category, ...]:
        return self.tree.leaves

    @property
    def categories(self) -> tuple[Category, ...]:
        return self.tree.categories

    def defining_matrix(self) -> np.ndarray:
        """One row per verb category: the value of every verb feature that is defining at the
        category (inherited or new), NaN elsewhere."""
        rows = np.full((len(self.categories), len(self.features)), np.nan)
        for i, category in enumerate(self.categories):
            mask = category.defining_mask()
            rows[i, mask] = category.free_values[mask]
        return rows


def verb_feature_set(verbs: VerbsConfig) -> FeatureSet:
    features = tuple(
        Feature(
            label=label,
            type=VERB_FEATURE_TYPE,
            index=i,
            free=True,
            layer=0,
            base_rate=verbs.base_rate,
            position=i - 1,
        )
        for i, label in enumerate(verbs.feature_labels, start=1)
    )
    return FeatureSet(features, max_chain_depth=0, warnings=())


def generate_verb_tree(config: Config, streams: Streams) -> VerbTaxonomy | None:
    """Generate the verb features and the verb tree, or None when ``verbs`` is null."""
    if config.verbs is None:
        return None
    features = verb_feature_set(config.verbs)
    rules = RuleSet(features, (), ())
    tree = build_tree(config.verbs.tree_settings(), rules, streams.verb_tree, streams.verb_tree)
    return VerbTaxonomy(features, rules, tree)
