"""The event-type tree: event-type features and the tree of two-place event types.

Two-place event types are generated by the taxonomy's own tree machinery, applied to a second
tree (``docs/specs/WORLD_AND_LANGUAGE.md``, "Event types"; Part B of
``docs/specs/TAXONOMY_RELATIONS.md``, with "verb" read as "event type"). The event-type features
``EVENTFEAT.<n>`` are binary, all free, with one shared base rate, and have no rules among
themselves. The tree is built exactly like the category tree (superordinates, roles, children,
distinct leaves) from ``event_types.binary.taxonomy`` and ``event_types.binary.inheritance``,
drawing everything from the ``world:event_tree`` stream. The leaves of the tree are the event
types ``EVENTTYPE2.<path>``; the internal nodes are categories of event types. Event types have
no instances. With depth 1 and no defining features, event types are independent of each other.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from semantic_world.taxonomy.features import Feature, FeatureSet
from semantic_world.taxonomy.rules import RuleSet
from semantic_world.taxonomy.tree import Category, Role, Tree, build_tree
from semantic_world.world.config import BinaryConfig

EVENT_FEATURE_TYPE = "event_feature"


@dataclass(frozen=True)
class EventTree:
    features: FeatureSet
    """The event-type features ``EVENTFEAT.1`` to ``EVENTFEAT.<count>``, all free."""
    rules: RuleSet
    """An empty rule set over the event-type features (they have no rules)."""
    tree: Tree
    """The event-type categories, labelled ``EVENTTYPE2.1``, ``EVENTTYPE2.1.1``, ...; the leaves
    are the event types."""

    @property
    def event_types(self) -> tuple[Category, ...]:
        """The two-place event types proper: the leaves of the tree."""
        return self.tree.leaves

    @property
    def categories(self) -> tuple[Category, ...]:
        """Every node of the tree, in category order."""
        return self.tree.categories

    def defining_matrix(self) -> np.ndarray:
        """One row per node: the value of every event-type feature that is defining at the node
        (inherited or new), NaN elsewhere."""
        rows = np.full((len(self.categories), len(self.features)), np.nan)
        for i, category in enumerate(self.categories):
            mask = category.defining_mask()
            rows[i, mask] = category.free_values[mask]
        return rows


def redraw_event_features(
    event_type: Category, binary: BinaryConfig, base_rates: np.ndarray, rng: np.random.Generator
) -> np.ndarray:
    """A fresh draw of an event type's non-defining features from its parent, as the
    distinct-leaves check does: defining features copy the parent, characteristic ones copy with
    the parent level's characteristic probability, undiagnostic ones come from the base rate. An
    event type without a parent draws every feature from the base rates."""
    parent = event_type.parent
    if parent is None:
        return (rng.random(len(base_rates)) < base_rates).astype(np.uint8)
    copy_probability = binary.inheritance.characteristic_probability[parent.level - 1]
    u = rng.random(len(base_rates))
    values = parent.free_values.copy()
    characteristic = parent.roles == Role.CHARACTERISTIC
    values[characteristic] ^= (u[characteristic] >= copy_probability).astype(np.uint8)
    undiagnostic = parent.roles == Role.UNDIAGNOSTIC
    values[undiagnostic] = (u[undiagnostic] < base_rates[undiagnostic]).astype(np.uint8)
    return values


def event_feature_set(binary: BinaryConfig) -> FeatureSet:
    features = tuple(
        Feature(
            label=label,
            type=EVENT_FEATURE_TYPE,
            index=i,
            free=True,
            layer=0,
            base_rate=binary.base_rate,
            position=i - 1,
        )
        for i, label in enumerate(binary.feature_labels, start=1)
    )
    return FeatureSet(features, max_chain_depth=0, warnings=())


def generate_event_tree(binary: BinaryConfig | None, rng: np.random.Generator) -> EventTree | None:
    """Generate the event-type features and the event-type tree from the ``world:event_tree``
    stream, or None when the world has no two-place event types."""
    if binary is None:
        return None
    features = event_feature_set(binary)
    rules = RuleSet(features, (), ())
    tree = build_tree(binary.tree_settings(), rules, rng, rng)
    return EventTree(features, rules, tree)


__all__ = [
    "EVENT_FEATURE_TYPE",
    "EventTree",
    "event_feature_set",
    "generate_event_tree",
    "redraw_event_features",
]
